import Head from 'next/head';
import { BiUserPlus } from "react-icons/bi";
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css';
import Table from '@/Components/Table';
import Form from '@/Components/Form';
import useToggle from '@/helpers/useToggle';

const inter = Inter({ subsets: ['latin'] })

// fetch data on server side.
export const getStaticProps = async ()=>{
  const data = await fetch('http://localhost:3000/api/users');
  const users = await data.json();
  return {
      props:{
          users
      }
  }
}

export default function Home({users}) {
  const [visible, toggle] = useToggle(); // Custom toggle hook.
  return (
    <section>
      <Head>
        <title>CRUD Application.</title>
        <meta name="description" content="Generated by Create Next App." />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='py-5'>
        <h1 className='text-xl md:text-5xl text-center font-bold py-10'>POC</h1>

        <div className='container mx-auto flex justify-between py-5 border-b'>
          <div className='left flex gap-3'>
            <button className='flex bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-gray-50 hover:border-indigo-500 hover:text-gray-800' onClick={toggle}>
              ADD NEW USER<span className='px-1'><BiUserPlus size={23}></BiUserPlus></span>
            </button>
          </div>
        </div>

        {/*FORM COMPONENT*/}
        {visible ?<Form></Form> : <></>}

        {/* TABLE COMPONENT */}
        <div className='container mx-auto'>
          <Table users={users}/>
        </div>

      </main>
    </section>
  )
}
